In [18]:
!pip install mediapipe opencv-python pandas scikit-learn

Requirement already satisfied: mediapipe in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (0.10.11)
Requirement already satisfied: opencv-python in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (4.10.0.84)
Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (2.0.3)
Requirement already satisfied: scikit-learn in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (1.3.2)
Requirement already satisfied: attrs>=19.1.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from mediapipe) (24.3.0)
Requirement already satisfied: jax in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from mediapipe) (0.4.13)
Requirement already satisfied: matplotlib in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from mediapipe) (3.7.5)
Requirement already satisfied: flatbuffers>=2.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from mediapipe) (24.12.23)
Requirement already satisfied: sounddevice>=0.4.4 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from mediapipe) (0.5.1)
Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from mediapipe) (1.24.4)
Requirement already satisfied: absl-py in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from mediapipe) (2.1.0)
Requirement already satisfied: opencv-contrib-python in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from mediapipe) (4.10.0.84)
Requirement already satisfied: protobuf<4,>=3.11 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from mediapipe) (3.20.3)
Requirement already satisfied: CFFI>=1.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from sounddevice>=0.4.4->mediapipe) (1.17.1)
Requirement already satisfied: pycparser in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe) (2.22)
Requirement already satisfied: tzdata>=2022.1 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: scipy>=1.5.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: ml-dtypes>=0.1.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from jax->mediapipe) (0.2.0)
Requirement already satisfied: importlib-metadata>=4.6 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from jax->mediapipe) (8.5.0)
Requirement already satisfied: opt-einsum in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from jax->mediapipe) (3.4.0)
Requirement already satisfied: zipp>=3.20 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from importlib-metadata>=4.6->jax->mediapipe) (3.20.2)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->mediapipe) (24.2)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->mediapipe) (6.4.5)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->mediapipe) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->mediapipe) (3.1.4)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->mediapipe) (0.12.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->mediapipe) (10.4.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->mediapipe) (4.55.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->mediapipe) (1.1.1)

WARNING: You are using pip version 21.1.1; however, version 24.3.1 is available.
You should consider upgrading via the 'c:\users\lenovo\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.

In [1]:
import mediapipe as mp
import cv2
import numpy as np
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

In [4]:
# Video Feed
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, image = cap.read()
    cv2.imshow('Mediapipe Feed', image)

    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [2]:
cap = cv2.VideoCapture(0)
## Setup mediapipe instance
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, image = cap.read()

        # Recolor Feed
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False

        # Make Detections
        results = pose.process(image)

        # Recolor image back to BGR for rendering
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)
        
        
        cv2.imshow('Mediapipe Feed', image)
    
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

In [6]:
cap = cv2.VideoCapture(0)

# Getting the video specs from the camera
height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
fps = cap.get(cv2.CAP_PROP_FPS)

videoWriter = cv2.VideoWriter('deadlift.avi', cv2.VideoWriter_fourcc('P', 'I', 'M', '1'), fps, (int(width), int(height)))

while cap.isOpened():
    ret, frame = cap.read()

    try:
        cv2.imshow('Press', frame)
        videoWriter.write(frame)
    except Exception as e:
        break

    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

cap.release()
videoWriter.release()
cv2.destroyAllWindows()

In [3]:
import csv 
import os 
import numpy as np
from matplotlib import pyplot as plt

In [4]:
landmarks = ['class']
for val in range(1, 33+1):
    landmarks += ['x{}'.format(val), 'y{}'.format(val), 'z{}'.format(val), 'v{}'.format(val)]

In [9]:
landmarks[1:]

['x1',
 'y1',
 'z1',
 'v1',
 'x2',
 'y2',
 'z2',
 'v2',
 'x3',
 'y3',
 'z3',
 'v3',
 'x4',
 'y4',
 'z4',
 'v4',
 'x5',
 'y5',
 'z5',
 'v5',
 'x6',
 'y6',
 'z6',
 'v6',
 'x7',
 'y7',
 'z7',
 'v7',
 'x8',
 'y8',
 'z8',
 'v8',
 'x9',
 'y9',
 'z9',
 'v9',
 'x10',
 'y10',
 'z10',
 'v10',
 'x11',
 'y11',
 'z11',
 'v11',
 'x12',
 'y12',
 'z12',
 'v12',
 'x13',
 'y13',
 'z13',
 'v13',
 'x14',
 'y14',
 'z14',
 'v14',
 'x15',
 'y15',
 'z15',
 'v15',
 'x16',
 'y16',
 'z16',
 'v16',
 'x17',
 'y17',
 'z17',
 'v17',
 'x18',
 'y18',
 'z18',
 'v18',
 'x19',
 'y19',
 'z19',
 'v19',
 'x20',
 'y20',
 'z20',
 'v20',
 'x21',
 'y21',
 'z21',
 'v21',
 'x22',
 'y22',
 'z22',
 'v22',
 'x23',
 'y23',
 'z23',
 'v23',
 'x24',
 'y24',
 'z24',
 'v24',
 'x25',
 'y25',
 'z25',
 'v25',
 'x26',
 'y26',
 'z26',
 'v26',
 'x27',
 'y27',
 'z27',
 'v27',
 'x28',
 'y28',
 'z28',
 'v28',
 'x29',
 'y29',
 'z29',
 'v29',
 'x30',
 'y30',
 'z30',
 'v30',
 'x31',
 'y31',
 'z31',
 'v31',
 'x32',
 'y32',
 'z32',
 'v32',
 'x33',
 'y33',
 'z33',
 'v33']

In [5]:
with open('deadliftcoords.csv', mode='w', newline='') as f:
    csv_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    csv_writer.writerow(landmarks)

In [6]:
def export_landmarks(results, action):
    try:
        keypoints = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten().tolist()
        keypoints.insert(0, action)

        with open('deadliftcoords.csv', mode='a', newline='') as f:
            csv_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
            csv_writer.writerow(keypoints)
    except Exception as e:
        pass

In [12]:
results.pose_landmarks

landmark {
  x: 0.5144243836402893
  y: 0.617933988571167
  z: -2.124128818511963
  visibility: 0.9980666637420654
}
landmark {
  x: 0.5396050810813904
  y: 0.5288369059562683
  z: -2.039823055267334
  visibility: 0.9956858158111572
}
landmark {
  x: 0.5599950551986694
  y: 0.5268957018852234
  z: -2.0403060913085938
  visibility: 0.9961825013160706
}
landmark {
  x: 0.5785390734672546
  y: 0.5261946320533752
  z: -2.040497303009033
  visibility: 0.994062066078186
}
landmark {
  x: 0.46847003698349
  y: 0.5333936810493469
  z: -2.069533348083496
  visibility: 0.9969798922538757
}
landmark {
  x: 0.44101279973983765
  y: 0.5341511964797974
  z: -2.0698189735412598
  visibility: 0.9976654052734375
}
landmark {
  x: 0.4167899191379547
  y: 0.53743976354599
  z: -2.0706772804260254
  visibility: 0.9972737431526184
}
landmark {
  x: 0.6050971150398254
  y: 0.5579795241355896
  z: -1.4105749130249023
  visibility: 0.9946578741073608
}
landmark {
  x: 0.3718133568763733
  y: 0.5758684277534485
  z: -1.5356333255767822
  visibility: 0.9985430240631104
}
landmark {
  x: 0.5456528663635254
  y: 0.7053457498550415
  z: -1.8713037967681885
  visibility: 0.9965699315071106
}
landmark {
  x: 0.4717404246330261
  y: 0.7150791883468628
  z: -1.9078407287597656
  visibility: 0.9986324906349182
}
landmark {
  x: 0.781724214553833
  y: 0.9188974499702454
  z: -0.8396002650260925
  visibility: 0.9658445119857788
}
landmark {
  x: 0.18256154656410217
  y: 0.9734307527542114
  z: -1.0390598773956299
  visibility: 0.9822187423706055
}
landmark {
  x: 0.8992888331413269
  y: 1.3955405950546265
  z: -0.6708513498306274
  visibility: 0.07268930226564407
}
landmark {
  x: 0.030369769781827927
  y: 1.5009738206863403
  z: -0.8555294871330261
  visibility: 0.1121535673737526
}
landmark {
  x: 0.8739112615585327
  y: 1.6857670545578003
  z: -1.2515150308609009
  visibility: 0.012635278515517712
}
landmark {
  x: 0.15318617224693298
  y: 1.8377898931503296
  z: -1.356264352798462
  visibility: 0.015032438561320305
}
landmark {
  x: 0.8897982835769653
  y: 1.798917531967163
  z: -1.4002187252044678
  visibility: 0.02204253152012825
}
landmark {
  x: 0.1782948076725006
  y: 1.974919080734253
  z: -1.529567003250122
  visibility: 0.023123186081647873
}
landmark {
  x: 0.8517492413520813
  y: 1.7643661499023438
  z: -1.4948440790176392
  visibility: 0.03415227308869362
}
landmark {
  x: 0.21918757259845734
  y: 1.932262659072876
  z: -1.595713496208191
  visibility: 0.038289014250040054
}
landmark {
  x: 0.8326424360275269
  y: 1.7144265174865723
  z: -1.313668131828308
  visibility: 0.030203118920326233
}
landmark {
  x: 0.21759402751922607
  y: 1.8753008842468262
  z: -1.4020159244537354
  visibility: 0.03406544402241707
}
landmark {
  x: 0.6683753728866577
  y: 1.8523701429367065
  z: 0.008887602016329765
  visibility: 0.00035735004348680377
}
landmark {
  x: 0.30917924642562866
  y: 1.863646388053894
  z: -0.0033960267901420593
  visibility: 0.0003772504278458655
}
landmark {
  x: 0.6833240985870361
  y: 2.6241796016693115
  z: 0.004136235918849707
  visibility: 0.002142752055078745
}
landmark {
  x: 0.3758653700351715
  y: 2.604886054992676
  z: -0.3163710832595825
  visibility: 0.0007430609548464417
}
landmark {
  x: 0.6912199258804321
  y: 3.292872667312622
  z: 0.9043996930122375
  visibility: 8.0933328717947e-05
}
landmark {
  x: 0.39404064416885376
  y: 3.293839454650879
  z: 0.3674008250236511
  visibility: 5.399420842877589e-05
}
landmark {
  x: 0.6888112425804138
  y: 3.4119722843170166
  z: 0.9460848569869995
  visibility: 3.842559453914873e-05
}
landmark {
  x: 0.38202354311943054
  y: 3.417367696762085
  z: 0.4015243947505951
  visibility: 6.119305908214301e-05
}
landmark {
  x: 0.6795703768730164
  y: 3.513803005218506
  z: 0.19981475174427032
  visibility: 0.0002094102674163878
}
landmark {
  x: 0.4855237901210785
  y: 3.499222993850708
  z: -0.4613516926765442
  visibility: 0.0003144778311252594
}

In [13]:
export_landmarks(results, 'up')

In [7]:
cap = cv2.VideoCapture('deadlift.mov')

# Initiate Holistic Model
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()

        if not ret:
            print("Error: Failed to read frame or video ended.")
            break

        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False

        # Make Detection
        results = pose.process(image)

        # Recolor image back to BGR for rendering
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        # Draw Landmarks
        if results.pose_landmarks:
            mp_drawing.draw_landmarks(
                image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                mp_drawing.DrawingSpec(color=(255, 117, 66), thickness=2, circle_radius=4),
                mp_drawing.DrawingSpec(color=(245, 66, 230), thickness=2, circle_radius=2)
            )

        # Handle key inputs
        k = cv2.waitKey(1)
        if k == ord('u'):  # Key 'u'
            export_landmarks(results, 'up')
        elif k == ord('d'):  # Key 'd'
            export_landmarks(results, 'down')

        # Display the updated frame
        cv2.imshow('Raw Webcam Feed', image)

        # Break on 'q' key
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

Error: Failed to read frame or video ended.

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv('deadliftcoords.csv')

In [10]:
df.head()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z31,v31,x32,y32,z32,v32,x33,y33,z33,v33
0,up,0.694547,0.616383,-1.304696,0.991757,0.722814,0.551621,-1.189779,0.987484,0.739014,...,-0.051641,0.000194,0.599101,3.756694,-0.419500,0.000315,0.369751,3.696445,-1.022877,0.000295
1,up,0.656157,0.597722,-1.258037,0.990105,0.691885,0.535847,-1.148525,0.985271,0.711286,...,-0.027923,0.000180,0.614034,3.747467,-0.625185,0.000265,0.397755,3.693044,-0.936177,0.000260
2,up,0.619097,0.586409,-1.587585,0.992239,0.658598,0.515012,-1.467834,0.989812,0.678778,...,1.149938,0.000294,0.559395,3.722066,-0.411730,0.000219,0.299082,3.696514,0.186288,0.000330
3,up,0.620085,0.585433,-1.522377,0.992520,0.655824,0.512390,-1.402156,0.991140,0.675187,...,0.771493,0.000380,0.597989,3.748304,-0.374316,0.000232,0.317890,3.725776,-0.200738,0.000402
4,up,0.606679,0.583948,-1.515601,0.993553,0.641900,0.510098,-1.383289,0.992785,0.662271,...,1.403956,0.001007,0.519470,3.845253,-0.115655,0.000456,0.272464,3.845834,0.442995,0.001123

In [11]:
df.tail()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z31,v31,x32,y32,z32,v32,x33,y33,z33,v33
25,down,0.568408,0.532159,-1.365418,0.997800,0.594928,0.461374,-1.252921,0.996756,0.614982,...,0.169957,0.000386,0.629202,3.809341,-0.638294,0.000268,0.401479,3.783690,-0.824189,0.000351
26,down,0.568713,0.529871,-1.342661,0.997020,0.594311,0.459819,-1.229874,0.995307,0.614617,...,-0.060288,0.000297,0.645630,3.779224,-0.790034,0.000213,0.423735,3.745387,-1.057569,0.000302
27,down,0.572977,0.539692,-1.334296,0.996723,0.597557,0.469804,-1.224406,0.994527,0.617223,...,0.093650,0.000230,0.652485,3.770138,-0.609240,0.000176,0.424810,3.739010,-0.876841,0.000257
28,down,0.580031,0.551794,-1.323282,0.996448,0.605594,0.480476,-1.218144,0.993775,0.623245,...,0.161991,0.000184,0.662614,3.761544,-0.550097,0.000152,0.431300,3.734812,-0.806537,0.000222
29,down,0.592342,0.557713,-1.246566,0.996030,0.620593,0.486125,-1.141333,0.992781,0.635181,...,0.019914,0.000152,0.665624,3.753820,-0.533149,0.000143,0.431606,3.721257,-0.930676,0.000199

In [12]:
df[df['class'] == 'up']

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z31,v31,x32,y32,z32,v32,x33,y33,z33,v33
0,up,0.694547,0.616383,-1.304696,0.991757,0.722814,0.551621,-1.189779,0.987484,0.739014,...,-0.051641,0.000194,0.599101,3.756694,-0.419500,0.000315,0.369751,3.696445,-1.022877,0.000295
1,up,0.656157,0.597722,-1.258037,0.990105,0.691885,0.535847,-1.148525,0.985271,0.711286,...,-0.027923,0.000180,0.614034,3.747467,-0.625185,0.000265,0.397755,3.693044,-0.936177,0.000260
2,up,0.619097,0.586409,-1.587585,0.992239,0.658598,0.515012,-1.467834,0.989812,0.678778,...,1.149938,0.000294,0.559395,3.722066,-0.411730,0.000219,0.299082,3.696514,0.186288,0.000330
3,up,0.620085,0.585433,-1.522377,0.992520,0.655824,0.512390,-1.402156,0.991140,0.675187,...,0.771493,0.000380,0.597989,3.748304,-0.374316,0.000232,0.317890,3.725776,-0.200738,0.000402
4,up,0.606679,0.583948,-1.515601,0.993553,0.641900,0.510098,-1.383289,0.992785,0.662271,...,1.403956,0.001007,0.519470,3.845253,-0.115655,0.000456,0.272464,3.845834,0.442995,0.001123
5,up,0.587829,0.583994,-1.499113,0.994648,0.627433,0.509541,-1.362455,0.994340,0.647107,...,1.417087,0.001219,0.450379,3.843018,-0.035929,0.000520,0.201534,3.830162,0.415250,0.001303
6,up,0.582599,0.583540,-1.299044,0.995801,0.622965,0.509655,-1.160371,0.995436,0.642626,...,0.838602,0.001321,0.459380,3.834972,-0.298177,0.000504,0.206193,3.824095,-0.144271,0.001178
7,up,0.565083,0.572824,-1.195819,0.996916,0.611807,0.506039,-1.061907,0.996564,0.633543,...,1.199872,0.001394,0.470939,3.833035,-0.106939,0.000462,0.247060,3.812254,0.202880,0.001119
19,up,0.574830,0.559547,-1.428141,0.999583,0.604622,0.491604,-1.301073,0.999305,0.621324,...,0.910609,0.000504,0.567002,3.777690,-0.463458,0.000273,0.343930,3.768620,-0.011321,0.000417
20,up,0.600332,0.560937,-1.408687,0.999616,0.627185,0.493070,-1.274712,0.999290,0.643023,...,0.881608,0.000465,0.569679,3.794027,-0.440990,0.000273,0.347890,3.783993,-0.009506,0.000385
21,up,0.600632,0.561674,-1.410255,0.999572,0.628623,0.493495,-1.279945,0.999122,0.645132,...,0.732216,0.000460,0.586729,3.828800,-0.473485,0.000305,0.356938,3.823900,-0.160781,0.000370
22,up,0.601096,0.561790,-1.465105,0.999574,0.628717,0.493626,-1.332719,0.999107,0.645248,...,1.072866,0.000432,0.585974,3.829484,-0.280171,0.000297,0.356541,3.820780,0.141531,0.000345

In [13]:
X = df.drop('class', axis = 1) # Feature
y = df['class'] # target value

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)

In [15]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [17]:
pipelines= {
    'lr':make_pipeline(StandardScaler(), LogisticRegression()),
    'rc':make_pipeline(StandardScaler(), RidgeClassifier()),
    'rf':make_pipeline(StandardScaler(), RandomForestClassifier()),
    'gb':make_pipeline(StandardScaler(), GradientBoostingClassifier())
}

In [19]:
fit_models = {}
for algo, pipeline in pipelines.items():
    model = pipeline.fit(X_train, y_train)
    fit_models[algo] = model

In [20]:
fit_models

{'lr': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('logisticregression', LogisticRegression())]),
 'rc': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('ridgeclassifier', RidgeClassifier())]),
 'rf': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('randomforestclassifier', RandomForestClassifier())]),
 'gb': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('gradientboostingclassifier', GradientBoostingClassifier())])}

In [21]:
fit_models['rc'].predict(X_test)

array(['down', 'down', 'up', 'down', 'down', 'down', 'up', 'up', 'down'],
      dtype='<U4')

In [23]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
import pickle

In [25]:
for algo, model in fit_models.items():
    yhat = model.predict(X_test)
    print(algo, accuracy_score(y_test.values, yhat),
         precision_score(y_test.values, yhat, average="binary", pos_label="up"),
         recall_score(y_test.values, yhat, average="binary", pos_label="up"))

lr 0.8888888888888888 1.0 0.75
rc 0.6666666666666666 0.6666666666666666 0.5
rf 0.8888888888888888 1.0 0.75
gb 1.0 1.0 1.0

In [27]:
yhat = fit_models['rf'].predict(X_test)

In [28]:
yhat[:10]

array(['down', 'down', 'up', 'up', 'down', 'down', 'up', 'down', 'down'],
      dtype=object)

In [31]:
y_test

7       up
10    down
4       up
1       up
28    down
8     down
3       up
23    down
14    down
Name: class, dtype: object

In [30]:
with open('deadlift.pkl', 'wb') as f:
    pickle.dump(fit_models['rf'], f)

In [32]:
with open('deadlift.pkl', 'rb') as f:
    model = pickle.load(f)

In [33]:
X = pd.DataFrame([row], column=landmarks[1:])

NameError: name 'row' is not defined

In [37]:
cap = cv2.VideoCapture(0)
counter = 0
current_stage = ''
# Initiate holistic model
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()

        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False

        # Make Detections
        results = pose.process(image)

        # Recolor image back to the BGR for rendering
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                                mp_drawing.DrawingSpec(color=(245, 117, 66), thickness=2, circle_radius=4),
                                mp_drawing.DrawingSpec(color=(245, 66, 230), thickness=2, circle_radius=2)
                                 )
        try:
            row = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten().tolist()
            X = pd.DataFrame([row], columns=landmarks[1:])
            body_language_class = model.predict(X)[0]
            body_language_prob = model.predict_proba(X)[0]
            print(body_language_class, body_language_prob)
    
            if body_language_class == 'down' and body_language_prob[body_language_prob.argmax()] >= .7:
                current_stage = 'down'
            elif current_stage == 'down' and body_language == 'up' and body_language_prob[body_language_prob.argmax()] < 0.7:
                current_stage = 'up'
                counter += 1
                print(current_stage)
    
            # Get Status Box
            cv2.rectangle(image, (0,0), (250, 60), (245, 117, 16), -1)
    
            # Display Class
            cv2.putText(image, 'CLASS',
                       (95, 12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
            cv2.putText(image, body_language_class.split(' ')[0],
                       (95, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 1, cv2.LINE_AA)
            
            # Display Probability
            cv2.putText(image, 'COUNTER',
                       (180, 12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
            cv2.putText(image, str(counter),
                       (175, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 1, cv2.LINE_AA)
        
        except Exception as e:
            pass

        cv2.imshow('Raw Webcam Feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

up [0.49 0.51]
up [0.47 0.53]
up [0.47 0.53]
up [0.47 0.53]
up [0.47 0.53]
up [0.48 0.52]
up [0.48 0.52]
up [0.48 0.52]
up [0.48 0.52]
up [0.48 0.52]
up [0.49 0.51]
down [0.5 0.5]
down [0.5 0.5]
down [0.5 0.5]
down [0.5 0.5]
down [0.5 0.5]
up [0.49 0.51]
down [0.5 0.5]
down [0.5 0.5]
up [0.49 0.51]
up [0.49 0.51]
up [0.47 0.53]
up [0.48 0.52]
up [0.48 0.52]
up [0.49 0.51]
down [0.5 0.5]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
down [0.5 0.5]
down [0.51 0.49]
down [0.52 0.48]
down [0.52 0.48]
up [0.49 0.51]
up [0.49 0.51]
down [0.5 0.5]
up [0.47 0.53]
down [0.51 0.49]
down [0.5 0.5]
up [0.49 0.51]
up [0.49 0.51]
up [0.48 0.52]
up [0.44 0.56]
up [0.47 0.53]
up [0.49 0.51]
up [0.46 0.54]
up [0.46 0.54]
up [0.48 0.52]
down [0.51 0.49]
up [0.49 0.51]
down [0.57 0.43]
down [0.54 0.46]
down [0.54 0.46]
down [0.5 0.5]
up [0.49 0.51]
down [0.5 0.5]
down [0.51 0.49]
down [0.55 0.45]
up [0.48 0.52]
up [0.47 0.53]
up [0.48 0.52]
up [0.49 0.51]
down [0.55 0.45]
down [0.51 0.49]
up [0.49 0.51]
up [0.47 0.53]
up [0.45 0.55]
down [0.55 0.45]
down [0.58 0.42]
down [0.59 0.41]
down [0.58 0.42]
down [0.57 0.43]
down [0.57 0.43]
down [0.55 0.45]
down [0.55 0.45]
down [0.53 0.47]
down [0.53 0.47]
up [0.49 0.51]
down [0.5 0.5]
down [0.5 0.5]
down [0.5 0.5]
down [0.52 0.48]
down [0.53 0.47]
down [0.57 0.43]
down [0.52 0.48]
down [0.51 0.49]
down [0.51 0.49]
down [0.52 0.48]
down [0.51 0.49]
down [0.5 0.5]
up [0.48 0.52]
down [0.5 0.5]
down [0.54 0.46]
down [0.53 0.47]
down [0.56 0.44]
down [0.56 0.44]
down [0.58 0.42]
down [0.56 0.44]
down [0.56 0.44]
down [0.57 0.43]
down [0.56 0.44]
down [0.5 0.5]
down [0.51 0.49]
up [0.49 0.51]
up [0.49 0.51]
down [0.52 0.48]
up [0.48 0.52]
down [0.51 0.49]
down [0.5 0.5]
up [0.48 0.52]
up [0.45 0.55]
up [0.48 0.52]
up [0.44 0.56]
up [0.44 0.56]
up [0.45 0.55]
up [0.43 0.57]
up [0.43 0.57]
up [0.42 0.58]
up [0.44 0.56]
up [0.44 0.56]
up [0.46 0.54]
up [0.47 0.53]
up [0.47 0.53]
up [0.49 0.51]
up [0.49 0.51]
down [0.5 0.5]
down [0.5 0.5]
up [0.49 0.51]
up [0.49 0.51]
up [0.49 0.51]
up [0.48 0.52]
up [0.45 0.55]
up [0.48 0.52]
down [0.72 0.28]
down [0.76 0.24]
down [0.85 0.15]
down [0.84 0.16]
down [0.84 0.16]
down [0.81 0.19]
down [0.81 0.19]
down [0.81 0.19]
down [0.8 0.2]
down [0.8 0.2]
down [0.8 0.2]
down [0.8 0.2]
down [0.82 0.18]
down [0.83 0.17]
down [0.82 0.18]
down [0.83 0.17]
down [0.83 0.17]
down [0.82 0.18]
down [0.84 0.16]
down [0.87 0.13]
down [0.86 0.14]
down [0.88 0.12]
down [0.88 0.12]
down [0.85 0.15]
down [0.85 0.15]
down [0.85 0.15]
down [0.86 0.14]
down [0.86 0.14]
down [0.86 0.14]
down [0.85 0.15]
down [0.8 0.2]
down [0.78 0.22]
down [0.77 0.23]
down [0.78 0.22]
down [0.78 0.22]
down [0.75 0.25]
down [0.75 0.25]
down [0.77 0.23]
down [0.75 0.25]
down [0.76 0.24]
down [0.77 0.23]
down [0.75 0.25]
down [0.73 0.27]
down [0.73 0.27]
down [0.73 0.27]
down [0.73 0.27]
down [0.78 0.22]
down [0.77 0.23]
down [0.78 0.22]
down [0.78 0.22]
down [0.78 0.22]
down [0.76 0.24]
down [0.74 0.26]
down [0.74 0.26]
down [0.73 0.27]
down [0.73 0.27]
down [0.72 0.28]
down [0.72 0.28]
down [0.72 0.28]
down [0.74 0.26]
down [0.74 0.26]
down [0.73 0.27]
down [0.71 0.29]
down [0.72 0.28]
down [0.74 0.26]
down [0.76 0.24]
down [0.76 0.24]
down [0.77 0.23]
down [0.76 0.24]
down [0.71 0.29]
down [0.74 0.26]
down [0.82 0.18]
down [0.91 0.09]
down [0.9 0.1]
down [0.91 0.09]
down [0.9 0.1]
down [0.91 0.09]
down [0.92 0.08]
down [0.78 0.22]
down [0.76 0.24]
down [0.74 0.26]
down [0.8 0.2]
down [0.85 0.15]
down [0.86 0.14]
down [0.84 0.16]
down [0.81 0.19]
down [0.62 0.38]
up [0.44 0.56]
up [0.44 0.56]
up [0.4 0.6]
up [0.29 0.71]
down [0.5 0.5]
down [0.51 0.49]
up [0.49 0.51]
down [0.51 0.49]
down [0.51 0.49]
up [0.49 0.51]
up [0.49 0.51]
down [0.5 0.5]
down [0.54 0.46]
down [0.52 0.48]
up [0.49 0.51]
down [0.5 0.5]
up [0.45 0.55]
down [0.52 0.48]
down [0.54 0.46]
down [0.54 0.46]
down [0.55 0.45]
down [0.55 0.45]
down [0.55 0.45]
up [0.46 0.54]
down [0.54 0.46]
down [0.54 0.46]
down [0.55 0.45]
up [0.49 0.51]
up [0.49 0.51]
up [0.48 0.52]
down [0.82 0.18]
down [0.83 0.17]
down [0.82 0.18]
down [0.81 0.19]
down [0.83 0.17]
down [0.81 0.19]
down [0.81 0.19]
down [0.81 0.19]
down [0.8 0.2]
down [0.8 0.2]
down [0.8 0.2]
down [0.8 0.2]
down [0.81 0.19]
down [0.82 0.18]
down [0.8 0.2]
down [0.8 0.2]
down [0.8 0.2]
down [0.8 0.2]
down [0.82 0.18]
down [0.81 0.19]
down [0.83 0.17]
down [0.81 0.19]
down [0.77 0.23]
down [0.56 0.44]
down [0.51 0.49]
down [0.5 0.5]
down [0.54 0.46]
down [0.55 0.45]
down [0.55 0.45]
up [0.49 0.51]
down [0.51 0.49]
down [0.54 0.46]
down [0.53 0.47]
down [0.53 0.47]
up [0.48 0.52]
up [0.48 0.52]
up [0.49 0.51]
up [0.49 0.51]
down [0.51 0.49]
up [0.48 0.52]
up [0.49 0.51]
down [0.5 0.5]
up [0.46 0.54]
up [0.48 0.52]
up [0.48 0.52]
up [0.48 0.52]
up [0.45 0.55]
up [0.48 0.52]
up [0.48 0.52]
down [0.51 0.49]
up [0.49 0.51]
up [0.47 0.53]
down [0.72 0.28]
down [0.63 0.37]
down [0.66 0.34]
down [0.83 0.17]
down [0.84 0.16]
down [0.86 0.14]
down [0.88 0.12]
down [0.88 0.12]
down [0.89 0.11]
down [0.88 0.12]
down [0.87 0.13]
down [0.88 0.12]
down [0.89 0.11]
down [0.77 0.23]
down [0.65 0.35]
down [0.53 0.47]
down [0.74 0.26]
down [0.59 0.41]
down [0.51 0.49]
down [0.6 0.4]
down [0.63 0.37]
down [0.7 0.3]
down [0.72 0.28]
down [0.76 0.24]
down [0.75 0.25]
down [0.83 0.17]
down [0.68 0.32]
down [0.69 0.31]
down [0.68 0.32]
down [0.67 0.33]
down [0.81 0.19]
down [0.82 0.18]
down [0.82 0.18]
down [0.77 0.23]
down [0.78 0.22]
down [0.69 0.31]
down [0.83 0.17]
down [0.68 0.32]
down [0.69 0.31]
down [0.88 0.12]
down [0.86 0.14]
down [0.81 0.19]
down [0.85 0.15]
down [0.8 0.2]
down [0.86 0.14]
down [0.81 0.19]
down [0.84 0.16]
down [0.83 0.17]
down [0.81 0.19]
down [0.8 0.2]
down [0.81 0.19]
down [0.81 0.19]
down [0.82 0.18]
down [0.79 0.21]
down [0.76 0.24]
down [0.81 0.19]
down [0.82 0.18]
down [0.82 0.18]
down [0.82 0.18]
down [0.81 0.19]
down [0.84 0.16]
down [0.74 0.26]
down [0.74 0.26]
down [0.84 0.16]
down [0.81 0.19]
down [0.79 0.21]
up [0.4 0.6]
up [0.41 0.59]
up [0.41 0.59]
up [0.42 0.58]
up [0.41 0.59]
up [0.43 0.57]
up [0.46 0.54]
up [0.49 0.51]
up [0.46 0.54]
up [0.46 0.54]
up [0.47 0.53]
down [0.5 0.5]
up [0.48 0.52]
up [0.49 0.51]
up [0.48 0.52]
up [0.46 0.54]
up [0.47 0.53]
up [0.47 0.53]
up [0.46 0.54]
up [0.46 0.54]
up [0.47 0.53]
up [0.47 0.53]
up [0.45 0.55]
up [0.44 0.56]
up [0.44 0.56]
up [0.44 0.56]
up [0.44 0.56]
up [0.46 0.54]
up [0.45 0.55]
up [0.46 0.54]
up [0.45 0.55]
up [0.45 0.55]
up [0.45 0.55]
up [0.44 0.56]
up [0.44 0.56]
up [0.44 0.56]
up [0.44 0.56]
up [0.44 0.56]
up [0.43 0.57]
up [0.43 0.57]
up [0.44 0.56]
up [0.43 0.57]
up [0.43 0.57]
up [0.44 0.56]
up [0.45 0.55]
up [0.45 0.55]
up [0.46 0.54]
up [0.45 0.55]
up [0.47 0.53]
up [0.45 0.55]
up [0.44 0.56]
up [0.45 0.55]
up [0.45 0.55]
up [0.44 0.56]
up [0.44 0.56]
up [0.46 0.54]
up [0.45 0.55]